# Generated by Django 4.2.3 on 2023-07-21 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_ispublic_chatroom_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='is_public',
        ),
        migrations.AddField(
            model_name='chatroommember',
            name='status',
            field=models.CharField(choices=[('joined', 'joined'), ('leaved', 'leaved')], default='joined', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='send_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.chatroommember'),
        ),
    ]
