# Generated by Django 4.2.3 on 2023-07-21 18:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_remove_chatroom_is_public_chatroommember_status_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatroommember',
            unique_together={('room', 'user')},
        ),
    ]
