# Generated by Django 4.2.3 on 2023-07-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chatroommember_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroommember',
            name='status',
            field=models.CharField(choices=[('joined', 'joined'), ('left', 'left')], default='joined', max_length=20),
        ),
    ]
